---
coverage:
  range: 85..100
  precision: 2
  round: down
  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_not_found: success
        informational: false
        only_pulls: false
ignore:
  - "tests"
comment:
  layout: "diff, files"
  require_changes: true
